/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista; 

import Controlador.Operaciones;
import Modelo.Docentes;
import Modelo.Estudiantes;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Interfaz_Docentes extends javax.swing.JFrame {
    

    Operaciones oper;
    /**
     * Creates new form Interfaz_Docentes2
     */
    public Interfaz_Docentes() {
        initComponents();
        this.setLocationRelativeTo(null);
        oper = new Operaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcedD = new javax.swing.JTextField();
        txtadm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnomD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDirInst = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnNuevoDoc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRegDoc = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnregresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcodD = new javax.swing.JTextField();
        txtapellD = new javax.swing.JTextField();
        txtcodE = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtaniolect = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtcedD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedDActionPerformed(evt);
            }
        });
        txtcedD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedDKeyTyped(evt);
            }
        });

        txtadm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtadmKeyTyped(evt);
            }
        });

        jLabel9.setText("Cédula_Docente:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtnomD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomDKeyTyped(evt);
            }
        });

        jLabel10.setText("Director/a_Institución:");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Código_Docente:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));

        jLabel2.setText("Código_Estudiante:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNuevoDoc.setText("Nuevo_Docente");
        btnNuevoDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNuevoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoDocActionPerformed(evt);
            }
        });

        jLabel3.setText("Administrador/a:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnRegDoc.setText("Registrar_Docente");
        btnRegDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRegDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegDocActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre_Docente:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnregresar.setText("Regresar");
        btnregresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        jLabel6.setText("Sexo:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setText("Unidad Educativa Fiscal \"Adolfo Jurado González\"");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Año_Lectivo:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Apellido_Docente:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtcodD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodDActionPerformed(evt);
            }
        });
        txtcodD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodDKeyTyped(evt);
            }
        });

        txtapellD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellDActionPerformed(evt);
            }
        });
        txtapellD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellDKeyTyped(evt);
            }
        });

        txtcodE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodEActionPerformed(evt);
            }
        });
        txtcodE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodEKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("DOCENTES");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0), 2));

        txtaniolect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaniolectKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)))
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(btnNuevoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtapellD, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnomD, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcedD, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDirInst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtadm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(txtcodE, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtcodD, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txtaniolect, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRegDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(jLabel11)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcodE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtadm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtnomD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtapellD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcedD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDirInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaniolect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoDoc)
                    .addComponent(btnRegDoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnregresar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcedDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedDActionPerformed

    private void btnNuevoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoDocActionPerformed
        // TODO add your handling code here:
        txtcodD.setText("");
        txtcodE.setText("");
        txtadm.setText("");
        txtnomD.setText("");
        txtapellD.setText("");
        txtcedD.setText("");
        txtDirInst.setText("");
        sexo.setSelectedItem("");
        txtaniolect.setText("");

    }//GEN-LAST:event_btnNuevoDocActionPerformed

    private void btnRegDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegDocActionPerformed
        // TODO add your handling code here:

        Docentes  docent = new Docentes (txtcodD.getText(), txtcodE.getText(),
            txtadm.getText(),
            txtnomD.getText(),
            txtapellD.getText(),
            Integer.parseInt(txtcedD.getText()),
            txtDirInst.getText(),
            sexo.getSelectedItem().toString(),
            Integer.parseInt(txtaniolect.getText()));
            oper.v_Docente(docent);
            
            Interfaz_Estudiantes intE = new Interfaz_Estudiantes(); 
            intE.setVisible(true);
            this.dispose();

    }//GEN-LAST:event_btnRegDocActionPerformed

    private void txtcodDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodDActionPerformed

    private void txtcodEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodEActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:
        Interfaz_principal2 intf = new Interfaz_principal2(); 
        intf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnregresarActionPerformed

    private void txtcodDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodDKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') evt.consume();
        
    }//GEN-LAST:event_txtcodDKeyTyped

    private void txtcodEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodEKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') evt.consume();
        
    }//GEN-LAST:event_txtcodEKeyTyped

    private void txtadmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadmKeyTyped
        
    }//GEN-LAST:event_txtadmKeyTyped

    private void txtnomDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomDKeyTyped
        char c= evt.getKeyChar();
        if(Character.isDigit(c))
        {
            getToolkit().beep();
            evt.consume();
            txtnomD.setCursor(null);
        }
        else if((int) evt.getKeyChar()>=32 && (int) evt.getKeyChar()<=47
        ||(int) evt.getKeyChar()>=58 && (int) evt.getKeyChar()<=64
        ||(int) evt.getKeyChar()>=91 && (int) evt.getKeyChar()<=96
        ||(int) evt.getKeyChar()>=123 && (int) evt.getKeyChar()<=255)
        {
            getToolkit().beep();
            evt.consume();
            txtnomD.setCursor(null);
        }
    }//GEN-LAST:event_txtnomDKeyTyped

    private void txtapellDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellDActionPerformed

    private void txtapellDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellDKeyTyped
        char c= evt.getKeyChar();
        if(Character.isDigit(c))
        {
            getToolkit().beep();
            evt.consume();
            txtapellD.setCursor(null);
        }
        else if((int) evt.getKeyChar()>=32 && (int) evt.getKeyChar()<=47
        ||(int) evt.getKeyChar()>=58 && (int) evt.getKeyChar()<=64
        ||(int) evt.getKeyChar()>=91 && (int) evt.getKeyChar()<=96
        ||(int) evt.getKeyChar()>=123 && (int) evt.getKeyChar()<=255)
        {
            getToolkit().beep();
            evt.consume();
            txtapellD.setCursor(null);
        }
    }//GEN-LAST:event_txtapellDKeyTyped

    private void txtcedDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedDKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txtcedDKeyTyped

    private void txtaniolectKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaniolectKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_txtaniolectKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Docentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Docentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Docentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Docentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Docentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoDoc;
    private javax.swing.JButton btnRegDoc;
    private javax.swing.JButton btnregresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField txtDirInst;
    private javax.swing.JTextField txtadm;
    private javax.swing.JTextField txtaniolect;
    private javax.swing.JTextField txtapellD;
    private javax.swing.JTextField txtcedD;
    private javax.swing.JTextField txtcodD;
    private javax.swing.JTextField txtcodE;
    private javax.swing.JTextField txtnomD;
    // End of variables declaration//GEN-END:variables
}
